ask/ask/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('qa.urls')),
    path('admin/', admin.site.urls),
]

ask/qa/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.signin, name='login'),
    path('signup/', views.signup, name='signup'),
    path('question/<int:question_id>/', views.question, name='question'),
    path('ask/', views.ask, name='ask'),
    path('popular/', views.popular, name='popular'),
    path('logout/', views.logout_view, name='logout'),
    path('question_like/', views.question_like, name='question_like')
]

ask/qa/models.py
from django.db import models
from django.contrib.auth.models import User


class QuestionManager(models.Manager):
    def new(self):
        return self.order_by('-added_at')
    
    def popular(self):
        return self.order_by('-rating')


class Question(models.Model):
    title = models.CharField(max_length=255)
    text = models.TextField()
    added_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # Use 'related name' to prevent an error due to creating managers with same name
    likes = models.ManyToManyField(User, related_name='likes_set', default=None, blank=True)
    rating = models.IntegerField(default=0)

    objects = QuestionManager()

    def rate(self, user):
        if self.likes.filter(id=user.id).exists():
            self.likes.remove(user)
            self.rating -= 1
        else:
            self.likes.add(user)
            self.rating += 1
        self.save()
        return self.rating


class Answer(models.Model):
    text = models.TextField()
    added_at = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

ask/qa/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.hashers import make_password

from .models import Question, Answer


def make_password_custom(password):
    """Customized make_password function."""
    return make_password(password, salt='some salt')


# class AnswerForm(forms.Form):
#     """From for adding a new answer."""
#     text = forms.CharField(widget=forms.Textarea)
#     question = forms.IntegerField(widget=forms.HiddenInput)

#     def clean(self):
#         try:
#             author = User.objects.get(username=self._user.username)
#         except User.DoesNotExist:
#             raise ValidationError('User not exist or unauthorized.')
#         self.cleaned_data['author'] = author

#     def save(self):
#         # We need a Question object to create an Answer object
#         question = Question.objects.get(pk=self.cleaned_data['question'])
#         self.cleaned_data['question'] = question
#         return Answer.objects.create(**self.cleaned_data)

class AnswerForm(forms.Form):
    """Form for adding a new answer."""
    text = forms.CharField(widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        self.question_id = kwargs.pop('question_id')
        super(AnswerForm, self).__init__(*args, **kwargs)
 
    def clean(self):
        try:
            author = User.objects.get(username=self._user.username)
        except User.DoesNotExist:
            raise ValidationError('User not exist or unauthorized.')
        self.cleaned_data['author'] = author

    def save(self):
        # We need a Question object to create an Answer object
        question = Question.objects.get(pk=self.question_id)
        self.cleaned_data['question'] = question
        return Answer.objects.create(**self.cleaned_data)


class AskForm(forms.Form):
    """Form for adding a new question."""
    title = forms.CharField(max_length=255)
    text = forms.CharField(widget=forms.Textarea)

    def clean(self):
        try:
            author = User.objects.get(username=self._user.username)
        except User.DoesNotExist:
            raise ValidationError('User "%s" does not exist.' % _user.username)
        self.cleaned_data['author'] = author

    def save(self):
        return Question.objects.create(**self.cleaned_data)


class SignupForm(forms.ModelForm):
    """Website signup form."""
    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'email':    forms.EmailInput(),
            'password': forms.PasswordInput()
        }

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.exclude(pk=self.instance.pk).filter(username=username).exists():
            raise ValidationError('User "%s" already exists.' % username)
        return username

    def clean_password(self):
        password = self.cleaned_data['password']
        validate_password(password)
        return make_password_custom(password)


class SigninForm(forms.ModelForm):
    """Website signup form."""
    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {'password': forms.PasswordInput()}

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        # Note: doesn't work when the superuser logs in, because
        # a different salt was used when creating his password.
        password = make_password_custom(password)
        try:
            # Note: with current MySQL settings collations are case insensitive,
            # so for example 'asd' and 'Asd' are considered the same.
            self.instance = User.objects.get(username=username, password=password)
        except User.DoesNotExist:
            raise ValidationError('Username or password is incorrect!')
        return self.cleaned_data

ask/qa/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import ensure_csrf_cookie

from .models import Question
from .forms import AnswerForm, AskForm, SignupForm, SigninForm


QUESTIONS_PER_PAGE = 10


def login_required_ajax(view):
    def wrapper(request, *args, **kwargs):
        if request.user.is_authenticated:
            return view(request, *args, **kwargs)
        return JsonResponse({'code': 'no_auth'})
    return wrapper


@ensure_csrf_cookie
def index(request):
    questions = Question.objects.new()
    paginator = Paginator(questions, QUESTIONS_PER_PAGE)
    page_num = request.GET.get('page')
    questions = paginator.get_page(page_num)
    return render(request, 'qa/index.html', {'questions': questions})


@ensure_csrf_cookie
def popular(request):
    questions = Question.objects.popular()
    paginator = Paginator(questions, QUESTIONS_PER_PAGE)
    page_num = request.GET.get('page')
    questions = paginator.get_page(page_num)
    return render(request, 'qa/popular.html', {'questions': questions})


def question(request, question_id):
    """
    Responsible for showing the page with answers to a question
    and processing the form for adding answers.
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST, question_id=question.id)
        form._user = request.user
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('question', args=(question.id,)))
    else:
        form = AnswerForm(question_id=question.id)
    return render(request, 'qa/question.html', {
        'question': question,
        'form': form
    })


@login_required(login_url='/login/')
def ask(request):
    """Responsible for processing the form for adding questions."""
    if request.method == 'POST':
        form = AskForm(request.POST)
        form._user = request.user
        if form.is_valid():
            question = form.save()
            return HttpResponseRedirect(reverse('question', args=(question.id,)))
    else:
        form = AskForm()
    return render(request, 'qa/ask.html', {'form': form})


def signup(request):
    logout(request)
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return HttpResponseRedirect(reverse('index'))
    else:
        form = SignupForm()
    return render(request, 'qa/signup.html', {'form': form})


def signin(request):
    if request.method == 'POST':
        form = SigninForm(request.POST)
        if form.is_valid():
            user = authenticate(
                request,
                username=request.POST['username'],
                password=request.POST['password']
            )
            login(request, user)
            return HttpResponseRedirect(reverse('index'))
    else:
        form = SigninForm()
    return render(request, 'qa/signin.html', {'form': form})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required_ajax
def question_like(request):
    """Responsible for processing likes on questions from users."""
    if request.method == 'POST':
        id = int(request.POST['question_id'])
        question = get_object_or_404(Question, id=id)
        rating = question.rate(request.user)
        return JsonResponse({'rating': rating, 'code': 'ok'})

ask/qa/templates/qa/ask.html
{% extends 'qa/base.html' %}

{% block content %}
<!-- Main content -->
<main class="container">
  <!-- Header -->  
  <p class="fs-5 text mt-3 mb-3">Your Question</p>
  {% for error in form.non_field_errors %}
      <div class="alert alert-danger">{{ error }}</div>
  {% endfor %}

  <!-- Question Form -->
  <form method="post" action="{% url 'ask' %}">
    {% csrf_token %}
    <div class="rounded-3 border shadow-sm p-3">
      <fieldset>
      {% for field in form %}
        <label class="form-label mb-auto">{{ field.label }}</label>
        <input class="form-control mb-1" type="{{ field.field.widget.input_type }}"
          name="{{ field.name }}"
        >
      {% endfor %}
      </fieldset>
      <div class="mt-3 text-center">
        <button type="submit" class="btn btn-primary">Ask</button>
      </div>
    </div>
  </form>

  <!-- <form class="form" method="post" action="{% url 'ask' %}">
      {% csrf_token %}
      <fieldset>
      {% for field in form %}
          <div class="control group {% if field.errors %}has-error{% endif %}">
              <label class="control-label">{{ field.label }}</label>
              <div class="controls">{{ field }}</div>
          </div>
      {% endfor %}
      </fieldset>
      <div class="form-actions">
          <button type="submit" class="btn btn-primary">Ask</button>
      </div>
  </form> End of Question Form -->
</main> <!-- End of Main Content -->
{% endblock %}

ask/qa/templates/qa/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous">
    <link href="{% static 'qa/css/custom.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'qa/img/favicon.ico' %}" rel="icon" type="image/x-icon">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    <script src="{% static 'qa/js/utils.js' %}"></script>

    <title>AskMe</title>
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg shadow-sm p-0 navbar-light bg-light">
      <div class="container-fluid">
        
        <!-- Brand -->
        <a class="navbar-brand p-0" href="{% url 'index' %}">
          <img src="{% static 'qa/img/logo1.png' %}" alt="Logo" height="70" width="140">
        </a>

        <!-- Toggler/collapse button -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
          aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navigation items -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Left Navbar -->
          <ul class="navbar-nav mb-lg-0 ms-lg-2">
            <li class="nav-item">
              <a href="{% url 'ask' %}" class="nav-link btn btn-primary">Ask Question</a>
            </li>
          </ul>

          <!-- Right Navbar -->
          <ul class="navbar-nav ms-auto">
          {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" role="button"
                data-bs-toggle="dropdown" aria-expanded="false">
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'logout' %}">Log out</a></li>
              </ul>
            </li>
            <span class="navbar-text me-5 pe-5">{{ user.get_username }}</span>
          {% else %}
            <li class="nav-item me-lg-2">
              <a href="{% url 'login' %}" class="nav-link btn btn-secondary">Log in</a>
            </li>
            <li class="nav-item me-lg-5">
              <a href="{% url 'signup' %}" class="nav-link btn btn-primary">Sign up</a>
            </li>
          {% endif %}
          </ul>
        </div> <!-- End of Navigation items -->

      </div> 
    </nav> <!-- End of Navigation -->

    {% block content %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous">
    </script>
  </body>
</html>

ask/qa/templates/qa/index.html
{% extends 'qa/base.html' %}

{% block content %}
<!-- Main Content -->
<main class="container">
  <!-- Main Header -->
  <div class="m-2 mb-3">
  {% block main_header %}
    <span class="fs-3 text me-3">New Questions</span>
    <a href="{% url 'popular' %}" class="text-decoration-none">Hot Questions</a>
  {% endblock %}
  </div>

  <!-- A way to pass URLs from Django templates to js scripts -->
  <input id="questionLikeBtnUrl" value="{% url 'question_like' %}" style="display:none;">
  <input id="questionLikeBtnLoginUrl" value="{% url 'login' %}" style="display:none;">

  <!-- Questions -->
  {% for question in questions %}
  <div class="container rounded border border-1 p-2 mb-3">
    <div class="row">
      <div id="alertPlaceholder{{ question.id }}"></div>
      <div class="col-3 col-md-1 border-end">
      </div>
      <div class="col-9 col-md-11">
        <a href="{% url 'question' question.id %}" class="text-decoration-none fs-5">
          {{ question.title }}
        </a>
      </div>
    </div>
    <div class="row">
      <div class="col-3 col-md-1 border-end">
        <p class="mb-auto">{{ question.author }}</p>
        <button class="btn btn-link text-dark p-0 border-0 btn-outline-light"
          id="question_like_btn{{ question.id }}" value="{{ question.id }}">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="50" fill="currentColor"
          class="bi bi-heart" viewBox="0 0 16 16">
            <path fill-rule="evenodd"
            d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92
            1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542
            6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878
            10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04
            7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1
            .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
          </svg>
        </button>
        <span id="question_rating{{ question.id }}">{{ question.rating }}</span>
        <small class="fw-light">{{ question.added_at|date:"SHORT_DATE_FORMAT" }}</small>
      </div>
      <div class="col-9 col-md-11">
        <div class="fs-6 text fw-light overflow-text">{{ question.text }}</div>
      </div>
    </div>
  </div>

  <script>
    $(`#question_like_btn{{ question.id }}`).click(function(e) {
        e.preventDefault()
        handleQuestionLikeBtn($(this))
      }
    );
  </script>
  {% endfor %}
    
  <!-- Pagination -->
  <nav>
    <ul class="pagination">
    {% if questions.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page=1">First</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ questions.previous_page_number }}">Previous</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link">First</span>
      </li>
      <li class="page-item disabled">
        <span class="page-link">Previous</span>
      </li>
    {% endif %}
      <li class="page-item disabled">
        <span class="page-link">
          Page {{ questions.number }} of {{ questions.paginator.num_pages }}
        </span>
      </li>
    {% if questions.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ questions.next_page_number }}">Next</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ questions.paginator.num_pages }}">Last</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link">Next</span>
      </li>
      <li class="page-item disabled">
        <span class="page-link">Last</span>
      </li>
    {% endif %}
    </ul>
  </nav>
</main> <!-- End of Main Content -->
{% endblock %}

ask/qa/templates/qa/popular.html
{% extends 'qa/index.html' %}

{% block main_header %}
  <span class="fs-3 text me-3">Hot Questions</span>
  <a href="{% url 'index' %}" class="text-decoration-none">New Questions</a>
{% endblock %}

ask/qa/templates/qa/question.html
{% extends 'qa/base.html' %}

{% block content %}
<!-- Main Content -->
<main class="container">
  <!-- Header -->
  <div class="container border-bottom mt-3 mb-2">
    <div class="row">
      <div class="col-3 col-md-1"></div>
      <div class="col-9 col-md-11">
        <p class="fs-3 text mb-2">{{ question.title }}</p>
      </div>
    </div>
    <div class="row">
      <div class="col-3 col-md-1">
        <p class="mb-auto">{{ question.author }}</p>
        <small class="fw-light">{{ question.added_at|date:"SHORT_DATE_FORMAT" }}</small>
      </div>
      <div class="col-9 col-md-11">
        <p class="fs-6 text">{{ question.text }}</p>
      </div>
    </div>
  </div>

  <!-- Answers -->
  {% for answer in question.answer_set.all %}
  <div class="container mb-3">
    <div class="row">
      <div class="col-3 col-md-1">
        <p class="mb-auto">{{ answer.author }}</p>
        <small class="fw-light">{{ answer.added_at|date:"SHORT_DATE_FORMAT" }}</small>
      </div>
      <div class="col-9 col-md-11">
        <p class="fs-6 text overflow-text">{{ answer.text }}</p>
      </div>
    </div>
  </div>
  {% endfor %}

  <!-- Answer Form -->
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">{{ error }}</div>
  {% endfor %}
  <form method="post" action="{% url 'question' question.id %}">
    <p class="fs-5 text mt-5 mb-2">Your Answer</p>
    
    {% csrf_token %}
    
    {% if not user.is_authenticated %}
    <div class="alert alert-danger">Please, authorize to answer.
        <a href="{% url 'login' %}" class="text-decoration-none">Log in</a>
    </div>
    {% endif %}
    
    <div class="rounded-3 border shadow-sm p-3">
      <fieldset>
      {% for field in form %}
        <input class="form-control mb-1" type="{{ field.field.widget.input_type }}"
          name="{{ field.name }}"
        >
      {% endfor %}
      </fieldset>

      <div class="mt-3 text-center">
        <button type="submit" class="btn btn-primary">Answer</button>
      </div>
    </div>
  </form> <!-- End of Answer Form -->
</main> <!-- End of Main Content -->
{% endblock %}

ask/qa/templates/qa/signin.html
{% extends 'qa/base.html' %}

{% block content %}
<div class="container-lg">
  <div class="row justify-content-center my-5">
    <div class="col-lg-6">
    {% for error in form.non_field_errors %}
      <div class="alert alert-danger">{{ error }}</div>
    {% endfor %}
      <!-- Login Form -->
      <form method="post" {% block form_action %} action="{% url 'login' %}" {% endblock %}>
        {% csrf_token %}
        <div class="rounded-3 border shadow-sm p-3">
          <fieldset>
          {% for field in form %}
            <label class="form-label mb-auto">{{ field.label }}</label>
            <input class="form-control mb-1" type="{{ field.field.widget.input_type }}"
              name="{{ field.name }}"
            >
          {% endfor %}
          </fieldset>
          <div class="mt-3 text-center">
            <button type="submit" class="btn btn-primary">
              {% block button_name %} Log in {% endblock %}
            </button>
          </div>
        </div>
      </form> <!-- End of Login Form -->
      <div class="mt-5 text-center">
      {% block additionals %}
        Don't have an account?
        <a href="{% url 'signup' %}" class="text-decoration-none">Sign up</a>
      {% endblock %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

ask/qa/templates/qa/signup.html
{% extends 'qa/signin.html' %}

{% block form_action %} action="{% url 'signup' %}" {% endblock %}

{% block button_name %} Sign up {% endblock %}

{% block additionals %}
  Already have an account?
  <a href="{% url 'login' %}" class="text-decoration-none">Log in</a>
{% endblock %}